# Generated by Django 5.1.8 on 2025-04-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.AlterModelOptions(
            name='davomat',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='davomat',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='davomat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='configapp.groupstudent'),
        ),
        migrations.AlterField(
            model_name='davomat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='configapp.student'),
        ),
        migrations.AddField(
            model_name='davomat',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='configapp.status'),
        ),
    ]
