# Generated by Django 5.1.8 on 2025-04-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_status_alter_davomat_options_remove_davomat_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
    ]
