# Generated by Django 5.1.6 on 2025-04-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_remove_homework_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
