# Generated by Django 5.1.6 on 2025-04-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0005_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='groupstudent',
            options={'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Uy vazifasi', 'verbose_name_plural': 'Uy vazifalari'},
        ),
        migrations.AlterModelOptions(
            name='homeworkreview',
            options={'verbose_name': 'Uy vazifasini baholash', 'verbose_name_plural': 'Uy vazifalarini baholashlar'},
        ),
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={'verbose_name': 'Uy vazifasini topshirish', 'verbose_name_plural': 'Uy vazifalarini topshirishlar'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'Oy', 'verbose_name_plural': 'Oylar'},
        ),
        migrations.AlterModelOptions(
            name='parents',
            options={'verbose_name': 'Ota-ona', 'verbose_name_plural': 'Ota-onalar'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': "To'lov turi", 'verbose_name_plural': "To'lov turlari"},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Xona', 'verbose_name_plural': 'Xonalar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Jadval', 'verbose_name_plural': 'Jadvallar'},
        ),
        migrations.AlterModelOptions(
            name='tabletype',
            options={'verbose_name': 'Jadval turi', 'verbose_name_plural': 'Jadval turlari'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
